version: '3.8'


services:
  db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - ${PG_DATA_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${WEB_PORT} --reload"
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db


volumes:
  postgres_data:
